[features]
seeds = false
skip-lint = false
[programs.localnet]
psyoracleutils = "GsaXofgSvd93FuJuNRcAfU6sCRNEc3wFjhdrrSkKFV4B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/linfish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
